name: built_site
description: Build static websites using Dart's build system
version: 0.2.10
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  analyzer: '^4.6.0'
  build: ^2.0.0
  charcode: ^1.2.0
  checked_yaml: ^2.0.1
  crypto: ^3.0.0
  glob: '^2.0.0'
  highlight: ^0.7.0
  html: ^0.15.0
  intl: ^0.17.0
  json_annotation: ^4.0.1
  markdown: ^6.0.0
  messagepack: ^0.2.1
  path: ^1.8.0
  sass: ^1.36.0
  source_span: ^1.8.1
  synchronized: ^3.0.0
  tar: ^0.5.0
  yaml: ^3.0.0

dev_dependencies:
  build_runner: ^2.0.0
  build_test: ^2.0.0
  build_version: ^2.0.1
  lints: ^2.0.0
  json_serializable: ^6.1.4
  test: ^1.17.0
